import * as React from 'react';

export const WINE_COLORS = [
    {color: "Rouge"},
    {color: "Rosé"},
    {color: "Blanc"},
]

export const DISHES_CATEGORIES = [
    {name: "Viande", color: "Rouge", img: require('../../assets/dishesCategories/Viande.jpg')},
    {name: "Poisson", color: "Blanc", img: require('../../assets/dishesCategories/Poisson.jpg')},
    {name: "Volaille", color: "Rouge", img: require('../../assets/dishesCategories/Volaille.jpg')},
    {name: "Pizza", color: "Rosé", img: require('../../assets/dishesCategories/Pizza.jpg')},
    {name: "Fruits", color: "Blanc", img: require('../../assets/dishesCategories/Fruits.jpg')},
    {name: "Chocolat", color: "Rouge", img: require('../../assets/dishesCategories/Chocolat.jpg')},
    {name: "Fromage", color: "Blanc", img: require('../../assets/dishesCategories/Fromage.jpg')},
]

export const DISHES = [
    {name: "Huîtres du Bassin d'Arcachon", country_id: 2, region_id: 12, color: "Blanc"},
    {name: "Caviar d'Aquitaine", country_id: 2, region_id: 12, color: "Blanc"},
    {name: "Poisson grillé avec une sauce beurre blanc", country_id: 2, region_id: 12, color: "Blanc"},
    {name: "Salade de pamplemousse et de crevettes", country_id: 2, region_id: 12, color: "Rosé"},
    {name: "Poulet basquaise", country_id: 2, region_id: 12, color: "Rosé"},
    {name: "Pissaladière", country_id: 2, region_id: 12, color: "Rosé"},
    {name: "Entrecôte bordelaise", country_id: 2, region_id: 12, color: "Rouge"},
    {name: "Confit de canard", country_id: 2, region_id: 12, color: "Rouge"},
    {name: "Agneau de Pauillac", country_id: 2, region_id: 12, color: "Rouge"},

    {name: "Choucroute garnie", country_id: 2, region_id: 13, color: "Blanc"},
    {name: "Tarte flambée alsacienne", country_id: 2, region_id: 13, color: "Blanc"},
    {name: "Quiche lorraine", country_id: 2, region_id: 13, color: "Blanc"},
    {name: "Flammekueche", country_id: 2, region_id: 13, color: "Rosé"},
    {name: "Buewespaetzle", country_id: 2, region_id: 13, color: "Rosé"},
    {name: "Tarte à l'oignon alsacienne", country_id: 2, region_id: 13, color: "Rosé"},
    {name: "Choucroute de poisson", country_id: 2, region_id: 13, color: "Rouge"},
    {name: "Munster fermier", country_id: 2, region_id: 13, color: "Rouge"},
    {name: "Baeckeoffe alsacien", country_id: 2, region_id: 13, color: "Rouge"},

    {name: "Poulet aux morilles", country_id: 2, region_id: 14, color: "Blanc"},
    {name: "Truite à la bourguignonne", country_id: 2, region_id: 14, color: "Blanc"},
    {name: "Escargots à la beaujolaise", country_id: 2, region_id: 14, color: "Blanc"},
    {name: "Saucisson de Lyon", country_id: 2, region_id: 14, color: "Rosé"},
    {name: "Salade lyonnaise", country_id: 2, region_id: 14, color: "Rosé"},
    {name: "Jambon persillé", country_id: 2, region_id: 14, color: "Rosé"},
    {name: "Charcuterie", country_id: 2, region_id: 14, color: "Rouge"},
    {name: "Filet mignon à la moutarde", country_id: 2, region_id: 14, color: "Rouge"},
    {name: "Tarte à l'oignon", country_id: 2, region_id: 14, color: "Rouge"},

    {name: "Poisson à la bordelaise", country_id: 2, region_id: 15, color: "Blanc"},
    {name: "Moules marinières", country_id: 2, region_id: 15, color: "Blanc"},
    {name: "Foie gras de canard", country_id: 2, region_id: 15, color: "Blanc"},
    {name: "Salade de tomates et de mozzarella", country_id: 2, region_id: 15, color: "Rosé"},
    {name: "Pizza margherita", country_id: 2, region_id: 15, color: "Rosé"},
    {name: "Ratatouille", country_id: 2, region_id: 15, color: "Rosé"},
    {name: "Côte de boeuf", country_id: 2, region_id: 15, color: "Rouge"},
    {name: "Magret de canard", country_id: 2, region_id: 15, color: "Rouge"},
    {name: "Blanquette de veau", country_id: 2, region_id: 15, color: "Rouge"},

    {name: "Escargots de Bourgogne", country_id: 2, region_id: 16, color: "Blanc"},
    {name: "Coquilles Saint-Jacques", country_id: 2, region_id: 16, color: "Blanc"},
    {name: "Boeuf bourguignon", country_id: 2, region_id: 16, color: "Blanc"},
    {name: "Quenelles de brochet", country_id: 2, region_id: 16, color: "Rosé"},
    {name: "Chateaubriand", country_id: 2, region_id: 16, color: "Rosé"},
    {name: "Epoisses", country_id: 2, region_id: 16, color: "Rosé"},
    {name: "Coq au vin", country_id: 2, region_id: 16, color: "Rouge"},
    {name: "Oeufs en meurette", country_id: 2, region_id: 16, color: "Rouge"},
    {name: "Charolais grillé", country_id: 2, region_id: 16, color: "Rouge"},

    {name: "Homard", country_id: 2, region_id: 17, color: "Blanc"},
    {name: "Sushi", country_id: 2, region_id: 17, color: "Blanc"},
    {name: "Crème brûlée", country_id: 2, region_id: 17, color: "Blanc"},
    {name: "Saumon fumé", country_id: 2, region_id: 17, color: "Rosé"},
    {name: "Tarte aux fraises", country_id: 2, region_id: 17, color: "Rosé"},
    {name: "Carpaccio de boeuf", country_id: 2, region_id: 17, color: "Rosé"},
    {name: "Côte de veau", country_id: 2, region_id: 17, color: "Rouge"},
    {name: "Risotto aux champignons", country_id: 2, region_id: 17, color: "Rouge"},
    {name: "Tiramisu", country_id: 2, region_id: 17, color: "Rouge"},

    {name: "Brocciu", country_id: 2, region_id: 18, color: "Blanc"},
    {name: "Veau aux olives", country_id: 2, region_id: 18, color: "Blanc"},
    {name: "Calamars farcis", country_id: 2, region_id: 18, color: "Blanc"},
    {name: "Figatellu", country_id: 2, region_id: 18, color: "Rosé"},
    {name: "Agneau corse", country_id: 2, region_id: 18, color: "Rosé"},
    {name: "Aubergines à la bonifacienne", country_id: 2, region_id: 18, color: "Rosé"},
    {name: "Civet de sanglier", country_id: 2, region_id: 18, color: "Rouge"},
    {name: "Canistrelli", country_id: 2, region_id: 18, color: "Rouge"},
    {name: "Assiette de charcuterie corse", country_id: 2, region_id: 18, color: "Rouge"},

    {name: "Fondue de Comté", country_id: 2, region_id: 19, color: "Blanc"},
    {name: "Truite meunière", country_id: 2, region_id: 19, color: "Blanc"},
    {name: "Poulet à la crème", country_id: 2, region_id: 19, color: "Blanc"},
    {name: "Salade de chèvre chaud", country_id: 2, region_id: 19, color: "Rosé"},
    {name: "Saucisson sec", country_id: 2, region_id: 19, color: "Rosé"},
    {name: "Pizza margherita", country_id: 2, region_id: 19, color: "Rosé"},
    {name: "Coq au vin jaune", country_id: 2, region_id: 19, color: "Rouge"},
    {name: "Canard confit", country_id: 2, region_id: 19, color: "Rouge"},
    {name: "Épaule d'agneau braisée", country_id: 2, region_id: 120, color: "Rouge"},

    {name: "Brandade de morue", country_id: 2, region_id: 20, color: "Blanc"},
    {name: "Bourride de poisson", country_id: 2, region_id: 20, color: "Blanc"},
    {name: "Cassoulet", country_id: 2, region_id: 20, color: "Blanc"},
    {name: "Soupe de poissons", country_id: 2, region_id: 20, color: "Rosé"},
    {name: "Tapenade", country_id: 2, region_id: 20, color: "Rosé"},
    {name: "Rouille", country_id: 2, region_id: 20, color: "Rosé"},
    {name: "Gardianne de taureau", country_id: 2, region_id: 20, color: "Rouge"},
    {name: "Morue à la catalane", country_id: 2, region_id: 20, color: "Rouge"},
    {name: "Cassoulet", country_id: 2, region_id: 20, color: "Rouge"},

    {name: "Crottin de Chavignol", country_id: 2, region_id: 21, color: "Blanc"},
    {name: "Saumon grillé", country_id: 2, region_id: 21, color: "Blanc"},
    {name: "Poulet rôti", country_id: 2, region_id: 21, color: "Blanc"},
    {name: "Rillettes de Tours", country_id: 2, region_id: 21, color: "Rosé"},
    {name: "Terrine de foie gras", country_id: 2, region_id: 21, color: "Rosé"},
    {name: "Rillons de Touraine", country_id: 2, region_id: 21, color: "Rosé"},
    {name: "Tarte aux champignons", country_id: 2, region_id: 21, color: "Rouge"},
    {name: "Poulet aux rillons", country_id: 2, region_id: 21, color: "Rouge"},
    {name: "Porc rôti à la sauge", country_id: 2, region_id: 21, color: "Rouge"},

    {name: "Ratatouille", country_id: 2, region_id: 22, color: "Blanc"},
    {name: "Bouillabaisse", country_id: 2, region_id: 22, color: "Blanc"},
    {name: "Salade niçoise", country_id: 2, region_id: 22, color: "Blanc"},
    {name: "Pissaladière", country_id: 2, region_id: 22, color: "Rosé"},
    {name: "Daube provençale", country_id: 2, region_id: 22, color: "Rosé"},
    {name: "Tapenade", country_id: 2, region_id: 22, color: "Rosé"},
    {name: "Tian de légumes", country_id: 2, region_id: 22, color: "Rouge"},
    {name: "Gigot d'agneau", country_id: 2, region_id: 22, color: "Rouge"},
    {name: "Aubergines à la provençale", country_id: 2, region_id: 22, color: "Rouge"},

    {name: "Fricassée de volaille", country_id: 2, region_id: 23, color: "Blanc"},
    {name: "Poisson grillé à la provençale", country_id: 2, region_id: 23, color: "Blanc"},
    {name: "Beignets de fleurs de courgette", country_id: 2, region_id: 23, color: "Blanc"},
    {name: "Salade de chèvre chaud", country_id: 2, region_id: 23, color: "Rosé"},
    {name: "Saucisson de Lyon", country_id: 2, region_id: 23, color: "Rosé"},
    {name: "Pissaladière", country_id: 2, region_id: 23, color: "Rosé"},
    {name: "Côte de boeuf grillée", country_id: 2, region_id: 23, color: "Rouge"},
    {name: "Daube provençale", country_id: 2, region_id: 23, color: "Rouge"},
    {name: "Gigot d'agneau aux herbes de Provence", country_id: 2, region_id: 23, color: "Rouge"},

    {name: "Fondue savoyarde", country_id: 2, region_id: 24, color: "Blanc"},
    {name: "Raclette", country_id: 2, region_id: 24, color: "Blanc"},
    {name: "Tartiflette", country_id: 2, region_id: 24, color: "Blanc"},
    {name: "Crozets au gratin", country_id: 2, region_id: 24, color: "Rosé"},
    {name: "Diots au vin blanc", country_id: 2, region_id: 24, color: "Rosé"},
    {name: "Polenta à la savoyarde", country_id: 2, region_id: 24, color: "Rosé"},
    {name: "Diots au vin rouge", country_id: 2, region_id: 24, color: "Rouge"},
    {name: "Gratin de ravioles", country_id: 2, region_id: 24, color: "Rouge"},
    {name: "Pormoniers de Savoie", country_id: 2, region_id: 24, color: "Rouge"},

    {name: "Foie gras de canard", country_id: 2, region_id: 25, color: "Blanc"},
    {name: "Magret de canard aux figues", country_id: 2, region_id: 25, color: "Blanc"},
    {name: "Cassoulet", country_id: 2, region_id: 25, color: "Blanc"},
    {name: "Salade périgourdine", country_id: 2, region_id: 25, color: "Rosé"},
    {name: "Garbure", country_id: 2, region_id: 25, color: "Rosé"},
    {name: "Tourtière béarnaise", country_id: 2, region_id: 25, color: "Rosé"},
    {name: "Confit de canard", country_id: 2, region_id: 25, color: "Rouge"},
    {name: "Axoa de veau", country_id: 2, region_id: 25, color: "Rouge"},
    {name: "Agneau de Pauillac", country_id: 2, region_id: 25, color: "Rouge"},

    {name: "Quenelles de brochet", country_id: 2, region_id: 26, color: "Blanc"},
    {name: "Chèvre chaud sur toast", country_id: 2, region_id: 26, color: "Blanc"},
    {name: "Coquilles Saint-Jacques", country_id: 2, region_id: 26, color: "Blanc"},
    {name: "Rillettes de Tours", country_id: 2, region_id: 26, color: "Rosé"},
    {name: "Saucisson brioché", country_id: 2, region_id: 26, color: "Rosé"},
    {name: "Tarte aux poireaux", country_id: 2, region_id: 26, color: "Rosé"},
    {name: "Rôti de porc à l'angevine", country_id: 2, region_id: 26, color: "Rouge"},
    {name: "Tarte au thon", country_id: 2, region_id: 26, color: "Rouge"},
    {name: "Poulet aux champignons", country_id: 2, region_id: 26, color: "Rouge"},

    {name: "Saint-Marcellin", country_id: 2, region_id: 27, color: "Blanc"},
    {name: "Tarte aux abricots", country_id: 2, region_id: 27, color: "Blanc"},
    {name: "Poisson à la provençale", country_id: 2, region_id: 27, color: "Blanc"},
    {name: "Daube provençale", country_id: 2, region_id: 27, color: "Rosé"},
    {name: "Tapenade", country_id: 2, region_id: 27, color: "Rosé"},
    {name: "Caviar d'aubergine", country_id: 2, region_id: 27, color: "Rosé"},
    {name: "Gigot d'agneau à la provençale", country_id: 2, region_id: 27, color: "Rouge"},
    {name: "Pissaladière", country_id: 2, region_id: 27, color: "Rouge"},
    {name: "Gratin de courgettes à la tomate", country_id: 2, region_id: 27, color: "Rouge"},
];